# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('west_end_market', '0003_auto_20190302_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 20, 13, 50, 240250, tzinfo=utc)),
        ),
    ]
